_wandb:
    value:
        cli_version: 0.23.0
        e:
            63v4kxvjgqo9fo4bp2oe8ns9c1jg2css:
                apple:
                    ecpuCores: 4
                    gpuCores: 16
                    memoryGb: 16
                    name: Apple M2 Pro
                    pcpuCores: 6
                    ramTotalBytes: "17179869184"
                    swapTotalBytes: "19327352832"
                codePath: /Users/lassestrandbygaard/Desktop/MSc Data Science/Deep Learning/Assignments/Assignment 4/hierarchical_VAE.ipynb
                codePathLocal: hierarchical_VAE.ipynb
                cpu_count: 10
                cpu_count_logical: 10
                disk:
                    /:
                        total: "494384795648"
                        used: "380342841344"
                email: last24ag@student.cbs.dk
                executable: /opt/miniconda3/bin/python
                git:
                    commit: c4271187e022dcde75b88d73819f7cd84e489388
                    remote: https://github.com/Lasbaskanenmas/Deep-Learning-4.git
                host: Lasses-MacBook-Pro.local
                memory:
                    total: "17179869184"
                os: macOS-15.6.1-arm64-arm-64bit
                program: /Users/lassestrandbygaard/Desktop/MSc Data Science/Deep Learning/Assignments/Assignment 4/hierarchical_VAE.ipynb
                python: CPython 3.12.2
                root: /Users/lassestrandbygaard/Desktop/MSc Data Science/Deep Learning/Assignments/Assignment 4
                startedAt: "2026-01-15T14:07:54.649468Z"
                writerId: 63v4kxvjgqo9fo4bp2oe8ns9c1jg2css
        m: []
        python_version: 3.12.2
        t:
            "1":
                - 1
                - 41
            "2":
                - 1
                - 41
            "3":
                - 2
                - 13
                - 16
            "4": 3.12.2
            "5": 0.23.0
            "8":
                - 1
            "12": 0.23.0
            "13": darwin-arm64
IWAE_K:
    value: 50
T:
    value: 3
hidden_dim:
    value: 784
latent_dim:
    value: 100
task:
    value: 1.4_iwae_evaluation
total_epochs:
    value: 100
warmup_epochs:
    value: 10
